### ISSUE TITLE
UnsatisfiedResolutionException

### ISSUE THREAD

**Issue by ASchmidt84** [sfxcode/sapphire-core#15]
Hi,
I try to use your module.
I have a Application object which extends from FXApp

My ApplicationController extends DefaultWindowController at applicationDidLaunch I replace the scene content with my LoginController

`lazy val loginController: LoginController = getController[LoginController](/*"/fxml/login/Login.fxml"*/)`

And now here is my problem. My gui is a subproject in sbt. I have a directory in resources with fxml/login and inside is Login.fxml

```
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.geometry.Insets?>
<?import javafx.scene.control.Button?>
<?import javafx.scene.control.ComboBox?>
<?import javafx.scene.control.Label?>
<?import javafx.scene.control.PasswordField?>
<?import javafx.scene.image.Image?>
<?import javafx.scene.image.ImageView?>
<?import javafx.scene.layout.ColumnConstraints?>
<?import javafx.scene.layout.GridPane?>
<?import javafx.scene.layout.HBox?>
<?import javafx.scene.layout.RowConstraints?>
<?import javafx.scene.text.TextFlow?>

<HBox alignment="CENTER" maxHeight="1.7976931348623157E308" maxWidth="1.7976931348623157E308" minHeight="-Infinity" minWidth="-Infinity" prefHeight="800.0" prefWidth="1280.0" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.com/fxml/1" fx:controller="controller.login.LoginController">
   <children>
      <GridPane alignment="CENTER" maxHeight="1.7976931348623157E308" maxWidth="1.7976931348623157E308" HBox.hgrow="NEVER">
        <columnConstraints>
          <ColumnConstraints hgrow="ALWAYS" minWidth="10.0" />
          <ColumnConstraints hgrow="ALWAYS" minWidth="10.0" />
        </columnConstraints>
        <rowConstraints>
            <RowConstraints fillHeight="false" minHeight="10.0" />
          <RowConstraints minHeight="10.0" vgrow="NEVER" />
          <RowConstraints minHeight="10.0" vgrow="NEVER" />
            <RowConstraints minHeight="10.0" vgrow="NEVER" />
          <RowConstraints minHeight="10.0" vgrow="NEVER" />
        </rowConstraints>
         <children>
            <Label text="%login.card" GridPane.hgrow="ALWAYS" GridPane.rowIndex="1">
               <GridPane.margin>
                  <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
               </GridPane.margin>
            </Label>
            <Label text="%login.password" GridPane.hgrow="ALWAYS" GridPane.rowIndex="2">
               <GridPane.margin>
                  <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
               </GridPane.margin>
            </Label>
            <PasswordField fx:id="cardField" maxWidth="1.7976931348623157E308" GridPane.columnIndex="1" GridPane.hgrow="ALWAYS" GridPane.rowIndex="1">
               <GridPane.margin>
                  <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
               </GridPane.margin>
            </PasswordField>
            <PasswordField fx:id="passwordField" maxWidth="1.7976931348623157E308" GridPane.columnIndex="1" GridPane.hgrow="ALWAYS" GridPane.rowIndex="2">
               <GridPane.margin>
                  <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
               </GridPane.margin>
            </PasswordField>
            <HBox alignment="CENTER" spacing="15.0" GridPane.columnSpan="2" GridPane.halignment="CENTER" GridPane.rowIndex="4" GridPane.valignment="CENTER">
               <children>
                  <Button mnemonicParsing="false" text="%login.login">
                     <graphic>
                        <ImageView fitHeight="64.0" fitWidth="64.0" pickOnBounds="true" preserveRatio="true">
                           <image>
                              <Image url="@../../img/debug_start.png" />
                           </image>
                        </ImageView>
                     </graphic></Button>
                  <Button mnemonicParsing="false" text="%login.reset">
                     <graphic>
                        <ImageView fitHeight="64.0" fitWidth="64.0" pickOnBounds="true" preserveRatio="true">
                           <image>
                              <Image url="@../../img/trash_bin.png" />
                           </image>
                        </ImageView>
                     </graphic></Button>
                  <Button mnemonicParsing="false" onAction="#quitAvalon" text="%login.cancel">
                     <graphic>
                        <ImageView fitHeight="64.0" fitWidth="64.0" pickOnBounds="true" preserveRatio="true">
                           <image>
                              <Image url="@../../img/close_window.png" />
                           </image>
                        </ImageView>
                     </graphic></Button>
               </children>
               <padding>
                  <Insets bottom="15.0" left="15.0" right="15.0" top="15.0" />
               </padding>
            </HBox>
            <TextFlow fx:id="informationText" textAlignment="CENTER" GridPane.columnSpan="2" GridPane.halignment="CENTER" GridPane.valignment="CENTER">
               <padding>
                  <Insets bottom="15.0" left="15.0" right="15.0" top="15.0" />
               </padding>
            </TextFlow>
            <Label text="%login.screen" GridPane.hgrow="ALWAYS" GridPane.rowIndex="3" GridPane.vgrow="NEVER">
               <GridPane.margin>
                  <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
               </GridPane.margin>
            </Label>
            <ComboBox fx:id="screenCombo" maxWidth="1.7976931348623157E308" GridPane.columnIndex="1" GridPane.hgrow="ALWAYS" GridPane.rowIndex="3">
               <GridPane.margin>
                  <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
               </GridPane.margin>
            </ComboBox>
         </children>
      </GridPane>
   </children>
</HBox>
```
My LoginController looks like this:
```
package controller.login

import com.sfxcode.sapphire.core.controller.ViewController
import com.sfxcode.sapphire.core.fxml.FxmlLoader
import com.sfxcode.sapphire.core.scene.ContentManager
import com.sfxcode.sapphire.core.value.{BeanConversions, FXBeanAdapter, KeyBindings}
import com.typesafe.scalalogging.LazyLogging
import controller.startUp.ApplicationController
import javafx.fxml.FXML
import javax.enterprise.context.ApplicationScoped
import scalafx.application.Platform
import scalafx.scene.control.ComboBox
import scalafx.scene.text.Text

@FxmlLoader(path = "/fxml/login/Login.fxml")
class LoginController extends ViewController with BeanConversions with LazyLogging {
  import scalafx.Includes._

  private val moduleMap = Map(
    "Lager" → "storageManagement",
    "Operator Ansicht" → "operatorView",
    "Mitarbeiter-Konfiguration" → "workerManagement"
  )

  @FXML
  var screenCombo: javafx.scene.control.ComboBox[String] = _

  @FXML
  var passwordField: javafx.scene.control.PasswordField = _

  @FXML
  var cardField: javafx.scene.control.PasswordField = _

  @FXML
  var informationText: javafx.scene.text.TextFlow = _

  override def didGainVisibilityFirstTime(): Unit = {
    super.didGainVisibilityFirstTime()

    val bindingList = List("cardField","passwordField")
    val bindings = KeyBindings(bindingList)

//    ContentManager()

  }

  override def didGainVisibility() {
    super.didGainVisibility()

    screenCombo.items() ++= moduleMap.values.toSeq
    informationText.getChildren += new Text("Guten Tag 2")
    cardField.requestFocus()
//    errorMessage.setText("")
//    email.setText("admin@logindemo.com")
  }

  def applicationController(): ApplicationController = {
    getBean[ApplicationController]()
  }

  /**
    * Beenden der Software in geordneter Reihenfolge
    * @param event
    */
  def quitAvalon(event: javafx.event.ActionEvent): Unit = {
    applicationController().shutdown()
  }

  /**
    * Setzt das Formular wieder zurück
    * @param event
    */
  def resetForm(event: javafx.event.ActionEvent): Unit = {
    cardField.text = ""
    passwordField.text = ""
    screenCombo.selectionModel().clearSelection()
  }

  def login(event: javafx.event.ActionEvent): Unit = {
    //
  }

}

```

If I start my application I get this error:
```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.IllegalStateException: can not load fxml from path [/fxml/login/Login.fxml]
	at com.sfxcode.sapphire.core.fxml.FxmlHandler.loadFromDocument(FxmlHandler.scala:53)
	at com.sfxcode.sapphire.core.fxml.FxmlHandler$$OwbNormalScopeProxy0.loadFromDocument(com/sfxcode/sapphire/core/fxml/FxmlHandler.java)
	at com.sfxcode.sapphire.core.fxml.FxmlLoading.getController(FxmlLoading.scala:38)
	at com.sfxcode.sapphire.core.fxml.FxmlLoading.getController$(FxmlLoading.scala:34)
	at com.sfxcode.sapphire.core.controller.WindowController.getController(WindowController.scala:20)
	at controller.startUp.ApplicationController.loginController$lzycompute(ApplicationController.scala:93)
	at controller.startUp.ApplicationController.loginController(ApplicationController.scala:93)
	at controller.startUp.ApplicationController.applicationDidLaunch(ApplicationController.scala:104)
	at com.sfxcode.sapphire.core.controller.DefaultWindowController.applicationStartup(DefaultWindowController.scala:21)
	at com.sfxcode.sapphire.core.controller.DefaultWindowController.startup(DefaultWindowController.scala:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.webbeans.event.ObserverMethodImpl.invoke(ObserverMethodImpl.java:404)
	at org.apache.webbeans.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:365)
	at org.apache.webbeans.event.NotificationManager.invokeObserverMethod(NotificationManager.java:818)
	at org.apache.webbeans.event.NotificationManager.fireEvent(NotificationManager.java:714)
	at org.apache.webbeans.container.BeanManagerImpl.fireEvent(BeanManagerImpl.java:495)
	at org.apache.webbeans.event.EventImpl.fire(EventImpl.java:83)
	at com.sfxcode.sapphire.core.cdi.ApplicationLauncher.launch(ApplicationLauncher.scala:27)
	at com.sfxcode.sapphire.core.cdi.ApplicationLauncher$$OwbNormalScopeProxy0.launch(com/sfxcode/sapphire/core/cdi/ApplicationLauncher.java)
	at com.sfxcode.sapphire.core.application.FXApplication.start(FXApplication.scala:18)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
Caused by: javafx.fxml.LoadException: 
/media/andre/DevelopmentSSD/scala/avalon/gui/target/scala-2.12/classes/fxml/login/Login.fxml:34

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2603)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2450)
	at com.sfxcode.sapphire.core.fxml.FxmlHandler.loadFromDocument(FxmlHandler.scala:43)
	... 31 more
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Api type [controller.login.LoginController] is not found with the qualifiers 
Qualifiers: [@javax.enterprise.inject.Default()]
for injection into Field Injection Point, field name :  instance, Bean Owner : [FXMLLoaderProvider, WebBeansType:MANAGED, Name:null, API Types:[java.lang.Object,com.sfxcode.sapphire.core.cdi.provider.FXMLLoaderProvider], Qualifiers:[javax.enterprise.inject.Default,javax.enterprise.inject.Any]]
	at org.apache.webbeans.util.InjectionExceptionUtil.throwUnsatisfiedResolutionException(InjectionExceptionUtil.java:60)
	at org.apache.webbeans.inject.instance.InstanceImpl.get(InstanceImpl.java:132)
	at com.sfxcode.sapphire.core.cdi.provider.FXMLLoaderProvider.$anonfun$createLoader$1(FXMLLoaderProvider.scala:20)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:938)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:980)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:227)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:752)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
	... 33 more

Process finished with exit code 1
```

If I add @ApplicationScoped to my LoginController my gui starts.
BUT!! all @FXML inside my controllers are null.

**Comment by sfxcode** [comment]
Hello, i tried to reproduce your issue with the actual version ("1.6.3").
It works fine so far. Also there is a working @FxmlLoader Sample inside the tutorial demo.
But I had a lot of changes (Cross compile 2.13, make scalafx usage optional in the last weeks and documentation, giter8 template has to be updated.

Please do NOT use @ApplicationScoped for ViewController ... it will break FXML loading

For instant help i have made a demo based on your sources with working login + change screen after login.
Hope it helps.
[avalon_working.zip](https://github.com/sfxcode/sapphire-core/files/3568918/avalon_working.zip)

Feel free to ask if there are problems left.

Greetings Tom

**Comment by ASchmidt84** [comment]
HI Tom,
I think i have a mistake. If I start run (play button in intellij) I get this error:

```
/opt/jdk/jdk-12.0.2/bin/java -javaagent:/opt/jetbrains-Toolbox/apps/IDEA-U/ch-0/192.6262.58/lib/idea_rt.jar=43329:/opt/jetbrains-Toolbox/apps/IDEA-U/ch-0/192.6262.58/bin -Dfile.encoding=UTF-8 -classpath /media/andre/DevelopmentSSD/scala/avalon_working/target/scala-2.12/classes:/home/andre/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.2.3.jar:/home/andre/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.25.jar:/home/andre/.ivy2/cache/org.scalafx/scalafx_2.12/jars/scalafx_2.12-12.0.1-R17.jar:/home/andre/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.8.jar:/home/andre/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.8.jar:/home/andre/.ivy2/cache/org.openjfx/javafx-web/jars/javafx-web-12.0.2-linux.jar:/home/andre/.ivy2/cache/org.openjfx/javafx-swing/jars/javafx-swing-12.0.2-linux.jar:/home/andre/.ivy2/cache/org.openjfx/javafx-media/jars/javafx-media-12.0.2-linux.jar:/home/andre/.ivy2/cache/org.openjfx/javafx-graphics/jars/javafx-graphics-12.0.2-linux.jar:/home/andre/.ivy2/cache/org.openjfx/javafx-fxml/jars/javafx-fxml-12.0.2-linux.jar:/home/andre/.ivy2/cache/org.openjfx/javafx-controls/jars/javafx-controls-12.0.2-linux.jar:/home/andre/.ivy2/cache/org.openjfx/javafx-base/jars/javafx-base-12.0.2-linux.jar:/home/andre/.ivy2/cache/org.kordamp.ikonli/ikonli-javafx/jars/ikonli-javafx-11.3.4.jar:/home/andre/.ivy2/cache/org.kordamp.ikonli/ikonli-fontawesome-pack/jars/ikonli-fontawesome-pack-11.3.4.jar:/home/andre/.ivy2/cache/org.kordamp.ikonli/ikonli-core/jars/ikonli-core-11.3.4.jar:/home/andre/.ivy2/cache/org.controlsfx/controlsfx/jars/controlsfx-11.0.0.jar:/home/andre/.ivy2/cache/org.apache.xbean/xbean-finder-shaded/jars/xbean-finder-shaded-4.13.jar:/home/andre/.ivy2/cache/org.apache.xbean/xbean-asm7-shaded/bundles/xbean-asm7-shaded-4.13.jar:/home/andre/.ivy2/cache/org.apache.openwebbeans/openwebbeans-spi/jars/openwebbeans-spi-2.0.11.jar:/home/andre/.ivy2/cache/org.apache.openwebbeans/openwebbeans-impl/jars/openwebbeans-impl-2.0.11.jar:/home/andre/.ivy2/cache/org.apache.deltaspike.core/deltaspike-core-impl/jars/deltaspike-core-impl-1.9.1.jar:/home/andre/.ivy2/cache/org.apache.deltaspike.core/deltaspike-core-api/jars/deltaspike-core-api-1.9.1.jar:/home/andre/.ivy2/cache/org.apache.deltaspike.cdictrl/deltaspike-cdictrl-owb/jars/deltaspike-cdictrl-owb-1.9.1.jar:/home/andre/.ivy2/cache/org.apache.deltaspike.cdictrl/deltaspike-cdictrl-api/jars/deltaspike-cdictrl-api-1.9.1.jar:/home/andre/.ivy2/cache/javax.interceptor/javax.interceptor-api/jars/javax.interceptor-api-1.2.jar:/home/andre/.ivy2/cache/javax.inject/javax.inject/jars/javax.inject-1.jar:/home/andre/.ivy2/cache/javax.enterprise/cdi-api/jars/cdi-api-2.0.jar:/home/andre/.ivy2/cache/javax.el/javax.el-api/jars/javax.el-api-3.0.0.jar:/home/andre/.ivy2/cache/javax.annotation/javax.annotation-api/jars/javax.annotation-api-1.3.2.jar:/home/andre/.ivy2/cache/de.odysseus.juel/juel-spi/jars/juel-spi-2.2.7.jar:/home/andre/.ivy2/cache/de.odysseus.juel/juel-impl/jars/juel-impl-2.2.7.jar:/home/andre/.ivy2/cache/de.odysseus.juel/juel-api/jars/juel-api-2.2.7.jar:/home/andre/.ivy2/cache/com.typesafe.scala-logging/scala-logging_2.12/bundles/scala-logging_2.12-3.9.2.jar:/home/andre/.ivy2/cache/com.typesafe/config/bundles/config-1.3.4.jar:/home/andre/.ivy2/cache/com.sfxcode.sapphire/sapphire-extension_2.12/jars/sapphire-extension_2.12-0.9.2.jar:/home/andre/.ivy2/cache/com.sfxcode.sapphire/sapphire-core_2.12/jars/sapphire-core_2.12-1.6.3.jar:/home/andre/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.2.3.jar Application
Sep. 03, 2019 12:05:24 NACHM. org.apache.webbeans.lifecycle.AbstractLifeCycle bootstrapApplication
INFO: OpenWebBeans Container is starting...
Sep. 03, 2019 12:05:24 NACHM. org.apache.webbeans.corespi.scanner.AbstractMetaDataDiscovery addWebBeansXmlLocation
INFO: added beans archive URL: file:/media/andre/DevelopmentSSD/scala/avalon_working/target/scala-2.12/classes/META-INF/beans.xml
Sep. 03, 2019 12:05:24 NACHM. org.apache.webbeans.corespi.scanner.AbstractMetaDataDiscovery addWebBeansXmlLocation
INFO: added beans archive URL: jar:file:/home/andre/.ivy2/cache/org.apache.deltaspike.core/deltaspike-core-impl/jars/deltaspike-core-impl-1.9.1.jar!/META-INF/beans.xml
Sep. 03, 2019 12:05:24 NACHM. org.apache.webbeans.corespi.scanner.AbstractMetaDataDiscovery addWebBeansXmlLocation
INFO: added beans archive URL: jar:file:/home/andre/.ivy2/cache/org.apache.deltaspike.core/deltaspike-core-api/jars/deltaspike-core-api-1.9.1.jar!/META-INF/beans.xml
Sep. 03, 2019 12:05:24 NACHM. org.apache.webbeans.corespi.scanner.AbstractMetaDataDiscovery addWebBeansXmlLocation
INFO: added beans archive URL: jar:file:/home/andre/.ivy2/cache/org.apache.deltaspike.cdictrl/deltaspike-cdictrl-owb/jars/deltaspike-cdictrl-owb-1.9.1.jar!/META-INF/beans.xml
Sep. 03, 2019 12:05:24 NACHM. org.apache.webbeans.corespi.scanner.AbstractMetaDataDiscovery addWebBeansXmlLocation
INFO: added beans archive URL: jar:file:/home/andre/.ivy2/cache/com.sfxcode.sapphire/sapphire-core_2.12/jars/sapphire-core_2.12-1.6.3.jar!/META-INF/beans.xml
Sep. 03, 2019 12:05:24 NACHM. org.apache.deltaspike.core.util.ProjectStageProducer initProjectStage
INFO: Computed the following DeltaSpike ProjectStage: Production
Sep. 03, 2019 12:05:24 NACHM. org.apache.webbeans.corespi.scanner.AbstractMetaDataDiscovery getBeanClassesPerBda
WARNING: Ignoring class [org.apache.deltaspike.cdise.owb.MockHttpSession] because it could not be loaded: java.lang.NoClassDefFoundError: javax/servlet/http/HttpSession 
Sep. 03, 2019 12:05:24 NACHM. org.apache.webbeans.corespi.scanner.AbstractMetaDataDiscovery getBeanClassesPerBda
WARNING: Ignoring class [org.apache.deltaspike.cdise.owb.OwbHelper] because it could not be loaded: java.lang.NoClassDefFoundError: javax/servlet/ServletContext 
Sep. 03, 2019 12:05:24 NACHM. org.apache.webbeans.corespi.scanner.AbstractMetaDataDiscovery getBeanClassesPerBda
WARNING: Ignoring class [org.apache.deltaspike.cdise.owb.MockServletContext] because it could not be loaded: java.lang.NoClassDefFoundError: javax/servlet/ServletContext 
Sep. 03, 2019 12:05:25 NACHM. org.apache.webbeans.config.BeansDeployer validateInjectionPoints
INFO: All injection points were validated successfully.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.webbeans.proxy.Unsafe (file:/home/andre/.ivy2/cache/org.apache.openwebbeans/openwebbeans-impl/jars/openwebbeans-impl-2.0.11.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.apache.webbeans.proxy.Unsafe
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Sep. 03, 2019 12:05:25 NACHM. org.apache.webbeans.lifecycle.AbstractLifeCycle bootstrapApplication
INFO: OpenWebBeans Container has started, it took [1320] ms.
12:05:25.563 [JavaFX Application Thread] INFO  c.startup.ApplicationController - start controller.startup.ApplicationController@7764b23c
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.IllegalStateException: can not load fxml from path [/fxml/login/Login.fxml]
	at com.sfxcode.sapphire.core.fxml.FxmlHandler.loadFromDocument(FxmlHandler.scala:53)
	at com.sfxcode.sapphire.core.fxml.FxmlHandler$$OwbNormalScopeProxy0.loadFromDocument(com/sfxcode/sapphire/core/fxml/FxmlHandler.java)
	at com.sfxcode.sapphire.core.fxml.FxmlLoading.getController(FxmlLoading.scala:38)
	at com.sfxcode.sapphire.core.fxml.FxmlLoading.getController$(FxmlLoading.scala:34)
	at com.sfxcode.sapphire.core.controller.WindowController.getController(WindowController.scala:19)
	at controller.startup.ApplicationController.loginController$lzycompute(ApplicationController.scala:15)
	at controller.startup.ApplicationController.loginController(ApplicationController.scala:15)
	at controller.startup.ApplicationController.applicationDidLaunch(ApplicationController.scala:22)
	at com.sfxcode.sapphire.core.controller.DefaultWindowController.applicationStartup(DefaultWindowController.scala:21)
	at com.sfxcode.sapphire.core.controller.DefaultWindowController.startup(DefaultWindowController.scala:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.webbeans.event.ObserverMethodImpl.invoke(ObserverMethodImpl.java:404)
	at org.apache.webbeans.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:365)
	at org.apache.webbeans.event.NotificationManager.invokeObserverMethod(NotificationManager.java:818)
	at org.apache.webbeans.event.NotificationManager.fireEvent(NotificationManager.java:714)
	at org.apache.webbeans.container.BeanManagerImpl.fireEvent(BeanManagerImpl.java:495)
	at org.apache.webbeans.event.EventImpl.fire(EventImpl.java:83)
	at com.sfxcode.sapphire.core.cdi.ApplicationLauncher.launch(ApplicationLauncher.scala:27)
	at com.sfxcode.sapphire.core.cdi.ApplicationLauncher$$OwbNormalScopeProxy0.launch(com/sfxcode/sapphire/core/cdi/ApplicationLauncher.java)
	at com.sfxcode.sapphire.core.application.FXApplication.start(FXApplication.scala:18)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
Caused by: java.lang.NullPointerException: inputStream is null.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2480)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2450)
	at com.sfxcode.sapphire.core.fxml.FxmlHandler.loadFromDocument(FxmlHandler.scala:43)
	... 31 more

Process finished with exit code 1
```

**Comment by sfxcode** [comment]
I use IntelliJ 2019.2 with Mac OSX Mojave

Working steps for me:
-> New -> Project from existing sources

<img width="1315" alt="Bildschirmfoto 2019-09-03 um 13 19 53" src="https://user-images.githubusercontent.com/4506602/64169318-d69e1a00-ce4d-11e9-81a7-9fdbe47d3ecb.png">

After Import and Compile IntelliJ looks like this:

<img width="562" alt="Bildschirmfoto 2019-09-03 um 13 17 21" src="https://user-images.githubusercontent.com/4506602/64169350-ef0e3480-ce4d-11e9-9982-c120fcde0cfa.png">

Run Application with Java 11 and 12 without problems.

Maybe it is an Linux issue. Have you tried  Demo Applications in Sapphire-Core ?

Hope that helps

**Comment by ASchmidt84** [comment]
Hi,
yes it tested all. Nothing works :(
Always NPE (inputstream is null)
I did it the same way.

It doesn't matter wheter i use sbt directly or intellij
I am using openjdk 11.0.2 and 12.0.2

**Comment by sfxcode** [comment]
maybe debugging FXMLoader in avalon_works project can help:

<img width="1786" alt="Bildschirmfoto 2019-09-03 um 13 54 01" src="https://user-images.githubusercontent.com/4506602/64171235-71005c80-ce52-11e9-84d5-b2e0afc6b870.png">

Inputstream from 

```
getClass.getResourceAsStream(path)
```

must not be null.

<img width="1289" alt="Bildschirmfoto 2019-09-03 um 13 56 12" src="https://user-images.githubusercontent.com/4506602/64171297-9b521a00-ce52-11e9-97c6-061dfc760561.png">

**Comment by ASchmidt84** [comment]
I know that null is inacceptable.But it is. I have tested with breakpoints. 
At FXMLHandler:40  the inputstream is still null.

**Comment by sfxcode** [comment]
Have you checked wether your login.fxml file is in your target folder after compile ?

Looks like a class loading problem. You can try to load other resources at the Debug breakpoint by evaluate Expression.

Or try at the breakpoint:

Thread.currentThread.getContextClassLoader.getResourceAsStream("/fxml/login/Login.fxml")

Maybe i can use this as fallback in FXMLLoader ...

Greetings Tom

**Comment by ASchmidt84** [comment]
How can I try this?

**Comment by sfxcode** [comment]
* Add a breakpoint at line 40 in FXMLLoader and start in Debug Mode  (see screenshot above)
* Use IntelliJ EvaluateExpression from right mouse menu and paste:

```
Thread.currentThread.getContextClassLoader.getResourceAsStream("/fxml/login/Login.fxml")
```

**Comment by ASchmidt84** [comment]
Hi.
With the command above I still get null.
If i change that to this `Thread.currentThread.getContextClassLoader.getResource("./fxml/login/login.fxml").openStream()` get an inputstream

**Comment by sfxcode** [comment]
can you please try:

```
Thread.currentThread.getContextClassLoader.getResourceAsStream("fxml/login/Login.fxml")
```

if it works, i can use your original path without trailing slash with getContextClassLoader as fallback

I will make a new sapphire-core version if it works

**Comment by ASchmidt84** [comment]
Hi,
I will try it tomorrow morning at 8 am (Germany time). But I think I tried at with the complete path to to the file, also without trailing slash and always I got a null. That was the reason why I changed it to my line above. With that line I also got data without the trailing dot.

**Comment by sfxcode** [comment]
```this.getClass().getResource(resourceName)```
 It tries to find the resource in the same package as 'this' class unless we use absolute path starting with '/'
```Thread.currentThread().getContextClassLoader().getResource(resourceName)```

A ClassLoader can be passed (shared) when creating a new thread using Thread.setContextClassLoader, so that different thread contexts can load each other classes/resources. If not set, the default is the ClassLoader context of the parent Thread. This method is not appropriate if we want to load resources inside the packages unless we use complete paths starting from root.

In the next version i will support both.

```scala

  def getResourceAsStream(path: String): InputStream = {
    var result: InputStream = getClass.getResourceAsStream(path)

    if (result == null) {
      val rootPath = {
        if (path.startsWith("/"))
          path.substring(1)
        else
          path
      }
      result = Thread.currentThread.getContextClassLoader.getResourceAsStream(rootPath)
    }
    result
  }
```

**Comment by ASchmidt84** [comment]
Good morning.
I tried it without the trailing slash. But still null. I checked also your method. It is still null.

**Comment by ASchmidt84** [comment]
Also the this.getClass gives always (event I try to get getResource(".")) null. I will investigate

**Comment by ASchmidt84** [comment]
Okay After trying and trying. Your way with getClass.getResourcesAsStream seemes to be working.
I will try your next version.

**Comment by ASchmidt84** [comment]
Okay. I am using now 1.6.4 And sorry. Null. 
![grafik](https://user-images.githubusercontent.com/5076186/64229783-18c96900-ceeb-11e9-9d80-2c37cc155bc7.png)

![grafik](https://user-images.githubusercontent.com/5076186/64229823-3565a100-ceeb-11e9-997b-a3b126bb374f.png)

![grafik](https://user-images.githubusercontent.com/5076186/64229866-53330600-ceeb-11e9-924e-529812a61128.png)

**Comment by ASchmidt84** [comment]
![grafik](https://user-images.githubusercontent.com/5076186/64230066-fab03880-ceeb-11e9-984f-b9d6a94ff504.png)
What about this?

**Comment by ASchmidt84** [comment]
SORRY!!! I had a spelling error! The login.fxml was typed as Login.fxml!

**Comment by ASchmidt84** [comment]
I dont know what is going on. I try it with your avalon. All worked fine. Now I try it with my avalon. And I get again an error. But! the inputstream is not null.
This is the error
`Api type [controller.login.LoginController] is not found with the qualifiers 
Qualifiers: [@javax.enterprise.inject.Default()]
for injection into Field Injection Point, field name :  instance, Bean Owner : [FXMLLoaderProvider, WebBeansType:MANAGED, Name:null, API Types:[java.lang.Object,com.sfxcode.sapphire.core.cdi.provider.FXMLLoaderProvider], Qualifiers:[javax.enterprise.inject.Default,javax.enterprise.inject.Any]]`

I have comment out the line (build.sbt) `"com.sfxcode.sapphire" %% "sapphire-extension" % "0.9.2"` and get the error above. If I comment the line in. The app is starting. But the ApplicationController does not have any effect. I see a grey window. Without my controller. And also the ApplicationController does not print out anything.

**Comment by ASchmidt84** [comment]
And now I have the solution! WHY, I dont know :)
I copied the directory META-INF with the file beans.xml
